# Generated by Django 4.0.5 on 2022-07-23 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 13, 11, 1, 90080, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='waste',
            name='id',
            field=models.CharField(default='zGe9n9ZuEeVeFwW', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
