# Generated by Django 4.0.2 on 2022-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='satviksnayak', max_length=50),
        ),
    ]
