# Generated by Django 4.0.5 on 2022-07-23 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_waste_entry_date_alter_waste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 23, 13, 14, 14, 490997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='waste',
            name='id',
            field=models.CharField(default='mxKIpZyKba1ojf7', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
